/* File: testmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Sun Mar 18 10:46:11 2018
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *test_error;
static PyObject *test_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifndef _LONG_DOUBLE
typedef long double long_double;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = test_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = test_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int long_double_from_pyobj(long_double* v,PyObject *obj,const char *errmess) {
  double d=0;
  if (PyArray_CheckScalar(obj)){
    if PyArray_IsScalar(obj, LongDouble) {
      PyArray_ScalarAsCtype(obj, v);
      return 1;
    }
    else if (PyArray_Check(obj) && PyArray_TYPE(obj)==NPY_LONGDOUBLE) {
      (*v) = *((npy_longdouble *)PyArray_DATA(obj));
      return 1;
    }
  }
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (long_double)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/***************************** solve_hill_problem *****************************/
static char doc_f2py_rout_test_hill_solver_solve_hill_problem[] = "\
solution,timestamps = solve_hill_problem(initial_state,dt,num_timesteps)\n\nWrapper for ``solve_hill_problem``.\
\n\nParameters\n----------\n"
"initial_state : input rank-1 array('g') with bounds (4)\n"
"dt : input float\n"
"num_timesteps : input int\n"
"\nReturns\n-------\n"
"solution : rank-2 array('g') with bounds (4,num_timesteps)\n"
"timestamps : rank-1 array('g') with bounds (num_timesteps)";
/*  */
static PyObject *f2py_rout_test_hill_solver_solve_hill_problem(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long_double*,long_double*,int*,long_double*,long_double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  long_double *initial_state = NULL;
  npy_intp initial_state_Dims[1] = {-1};
  const int initial_state_Rank = 1;
  PyArrayObject *capi_initial_state_tmp = NULL;
  int capi_initial_state_intent = 0;
  PyObject *initial_state_capi = Py_None;
  long_double dt = 0;
  PyObject *dt_capi = Py_None;
  int num_timesteps = 0;
  PyObject *num_timesteps_capi = Py_None;
  long_double *solution = NULL;
  npy_intp solution_Dims[2] = {-1, -1};
  const int solution_Rank = 2;
  PyArrayObject *capi_solution_tmp = NULL;
  int capi_solution_intent = 0;
  long_double *timestamps = NULL;
  npy_intp timestamps_Dims[1] = {-1};
  const int timestamps_Rank = 1;
  PyArrayObject *capi_timestamps_tmp = NULL;
  int capi_timestamps_intent = 0;
  static char *capi_kwlist[] = {"initial_state","dt","num_timesteps",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:test.hill_solver.solve_hill_problem",\
    capi_kwlist,&initial_state_capi,&dt_capi,&num_timesteps_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable num_timesteps */
    f2py_success = int_from_pyobj(&num_timesteps,num_timesteps_capi,"test.hill_solver.solve_hill_problem() 3rd argument (num_timesteps) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = long_double_from_pyobj(&dt,dt_capi,"test.hill_solver.solve_hill_problem() 2nd argument (dt) can't be converted to long_double");
  if (f2py_success) {
  /* Processing variable initial_state */
  initial_state_Dims[0]=4;
  capi_initial_state_intent |= F2PY_INTENT_IN;
  capi_initial_state_tmp = array_from_pyobj(NPY_LONGDOUBLE,initial_state_Dims,initial_state_Rank,capi_initial_state_intent,initial_state_capi);
  if (capi_initial_state_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting 1st argument `initial_state' of test.hill_solver.solve_hill_problem to C/Fortran array" );
  } else {
    initial_state = (long_double *)(PyArray_DATA(capi_initial_state_tmp));

  /* Processing variable timestamps */
  timestamps_Dims[0]=num_timesteps;
  capi_timestamps_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_timestamps_tmp = array_from_pyobj(NPY_LONGDOUBLE,timestamps_Dims,timestamps_Rank,capi_timestamps_intent,Py_None);
  if (capi_timestamps_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting hidden `timestamps' of test.hill_solver.solve_hill_problem to C/Fortran array" );
  } else {
    timestamps = (long_double *)(PyArray_DATA(capi_timestamps_tmp));

  /* Processing variable solution */
  solution_Dims[0]=4,solution_Dims[1]=num_timesteps;
  capi_solution_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_solution_tmp = array_from_pyobj(NPY_LONGDOUBLE,solution_Dims,solution_Rank,capi_solution_intent,Py_None);
  if (capi_solution_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting hidden `solution' of test.hill_solver.solve_hill_problem to C/Fortran array" );
  } else {
    solution = (long_double *)(PyArray_DATA(capi_solution_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(initial_state,&dt,&num_timesteps,solution,timestamps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_solution_tmp,capi_timestamps_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_solution_tmp == NULL) ... else of solution*/
  /* End of cleaning variable solution */
  }  /*if (capi_timestamps_tmp == NULL) ... else of timestamps*/
  /* End of cleaning variable timestamps */
  if((PyObject *)capi_initial_state_tmp!=initial_state_capi) {
    Py_XDECREF(capi_initial_state_tmp); }
  }  /*if (capi_initial_state_tmp == NULL) ... else of initial_state*/
  /* End of cleaning variable initial_state */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of num_timesteps*/
  /* End of cleaning variable num_timesteps */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of solve_hill_problem *************************/

/******************************* hill_ode_step *******************************/
static char doc_f2py_rout_test_hill_solver_hill_ode_step[] = "\
new_state = hill_ode_step(state,a_coeffs,b_coeffs,dt)\n\nWrapper for ``hill_ode_step``.\
\n\nParameters\n----------\n"
"state : input rank-1 array('g') with bounds (4)\n"
"a_coeffs : input rank-1 array('g') with bounds (4)\n"
"b_coeffs : input rank-1 array('g') with bounds (4)\n"
"dt : input float\n"
"\nReturns\n-------\n"
"new_state : rank-1 array('g') with bounds (4) and hill_ode_step storage";
/* #declfortranroutine# */
static PyObject *f2py_rout_test_hill_solver_hill_ode_step(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long_double*,long_double*,long_double*,long_double*,long_double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  long_double *hill_ode_step = NULL;
  npy_intp hill_ode_step_Dims[1] = {-1};
  const int hill_ode_step_Rank = 1;
  PyArrayObject *capi_hill_ode_step_tmp = NULL;
  int capi_hill_ode_step_intent = 0;
  long_double *state = NULL;
  npy_intp state_Dims[1] = {-1};
  const int state_Rank = 1;
  PyArrayObject *capi_state_tmp = NULL;
  int capi_state_intent = 0;
  PyObject *state_capi = Py_None;
  long_double *a_coeffs = NULL;
  npy_intp a_coeffs_Dims[1] = {-1};
  const int a_coeffs_Rank = 1;
  PyArrayObject *capi_a_coeffs_tmp = NULL;
  int capi_a_coeffs_intent = 0;
  PyObject *a_coeffs_capi = Py_None;
  long_double *b_coeffs = NULL;
  npy_intp b_coeffs_Dims[1] = {-1};
  const int b_coeffs_Rank = 1;
  PyArrayObject *capi_b_coeffs_tmp = NULL;
  int capi_b_coeffs_intent = 0;
  PyObject *b_coeffs_capi = Py_None;
  long_double dt = 0;
  PyObject *dt_capi = Py_None;
  static char *capi_kwlist[] = {"state","a_coeffs","b_coeffs","dt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:test.hill_solver.hill_ode_step",\
    capi_kwlist,&state_capi,&a_coeffs_capi,&b_coeffs_capi,&dt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable b_coeffs */
  b_coeffs_Dims[0]=4;
  capi_b_coeffs_intent |= F2PY_INTENT_IN;
  capi_b_coeffs_tmp = array_from_pyobj(NPY_LONGDOUBLE,b_coeffs_Dims,b_coeffs_Rank,capi_b_coeffs_intent,b_coeffs_capi);
  if (capi_b_coeffs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting 3rd argument `b_coeffs' of test.hill_solver.hill_ode_step to C/Fortran array" );
  } else {
    b_coeffs = (long_double *)(PyArray_DATA(capi_b_coeffs_tmp));

  /* Processing variable a_coeffs */
  a_coeffs_Dims[0]=4;
  capi_a_coeffs_intent |= F2PY_INTENT_IN;
  capi_a_coeffs_tmp = array_from_pyobj(NPY_LONGDOUBLE,a_coeffs_Dims,a_coeffs_Rank,capi_a_coeffs_intent,a_coeffs_capi);
  if (capi_a_coeffs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting 2nd argument `a_coeffs' of test.hill_solver.hill_ode_step to C/Fortran array" );
  } else {
    a_coeffs = (long_double *)(PyArray_DATA(capi_a_coeffs_tmp));

  /* Processing variable state */
  state_Dims[0]=4;
  capi_state_intent |= F2PY_INTENT_IN;
  capi_state_tmp = array_from_pyobj(NPY_LONGDOUBLE,state_Dims,state_Rank,capi_state_intent,state_capi);
  if (capi_state_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting 1st argument `state' of test.hill_solver.hill_ode_step to C/Fortran array" );
  } else {
    state = (long_double *)(PyArray_DATA(capi_state_tmp));

  /* Processing variable dt */
    f2py_success = long_double_from_pyobj(&dt,dt_capi,"test.hill_solver.hill_ode_step() 4th argument (dt) can't be converted to long_double");
  if (f2py_success) {
  /* Processing variable hill_ode_step */
  hill_ode_step_Dims[0]=4;
  capi_hill_ode_step_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_hill_ode_step_tmp = array_from_pyobj(NPY_LONGDOUBLE,hill_ode_step_Dims,hill_ode_step_Rank,capi_hill_ode_step_intent,Py_None);
  if (capi_hill_ode_step_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(test_error,"failed in converting hidden `hill_ode_step' of test.hill_solver.hill_ode_step to C/Fortran array" );
  } else {
    hill_ode_step = (long_double *)(PyArray_DATA(capi_hill_ode_step_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(hill_ode_step,state,a_coeffs,b_coeffs,&dt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_hill_ode_step_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_hill_ode_step_tmp == NULL) ... else of hill_ode_step*/
  /* End of cleaning variable hill_ode_step */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_state_tmp!=state_capi) {
    Py_XDECREF(capi_state_tmp); }
  }  /*if (capi_state_tmp == NULL) ... else of state*/
  /* End of cleaning variable state */
  if((PyObject *)capi_a_coeffs_tmp!=a_coeffs_capi) {
    Py_XDECREF(capi_a_coeffs_tmp); }
  }  /*if (capi_a_coeffs_tmp == NULL) ... else of a_coeffs*/
  /* End of cleaning variable a_coeffs */
  if((PyObject *)capi_b_coeffs_tmp!=b_coeffs_capi) {
    Py_XDECREF(capi_b_coeffs_tmp); }
  }  /*if (capi_b_coeffs_tmp == NULL) ... else of b_coeffs*/
  /* End of cleaning variable b_coeffs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of hill_ode_step ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_hill_solver_def[] = {
  {"solve_hill_problem",-1,{{-1}},0,NULL,(void *)f2py_rout_test_hill_solver_solve_hill_problem,doc_f2py_rout_test_hill_solver_solve_hill_problem},
  {"hill_ode_step",-1,{{-1}},0,NULL,(void *)f2py_rout_test_hill_solver_hill_ode_step,doc_f2py_rout_test_hill_solver_hill_ode_step},
  {NULL}
};

static void f2py_setup_hill_solver(char *solve_hill_problem,char *hill_ode_step) {
  int i_f2py=0;
  f2py_hill_solver_def[i_f2py++].data = solve_hill_problem;
  f2py_hill_solver_def[i_f2py++].data = hill_ode_step;
}
extern void F_FUNC_US(f2pyinithill_solver,F2PYINITHILL_SOLVER)(void (*)(char *,char *));
static void f2py_init_hill_solver(void) {
  F_FUNC_US(f2pyinithill_solver,F2PYINITHILL_SOLVER)(f2py_setup_hill_solver);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "test",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_test(void) {
#else
#define RETVAL
PyMODINIT_FUNC inittest(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = test_module = PyModule_Create(&moduledef);
#else
  m = test_module = Py_InitModule("test", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module test (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'test' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  hill_solver --- solve_hill_problem(),hill_ode_step()"".");
  PyDict_SetItemString(d, "__doc__", s);
  test_error = PyErr_NewException ("test.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "hill_solver", PyFortranObject_New(f2py_hill_solver_def,f2py_init_hill_solver));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"test");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
