!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_hill_solver_hill_ode_step (hill_ode_stepf2pywr&
     &ap, state, a_coeffs, b_coeffs, dt)
      use hill_solver, only : hill_ode_step
      real(kind=16) dt
      real(kind=16) state(4)
      real(kind=16) a_coeffs(4)
      real(kind=16) b_coeffs(4)
      real(kind=16) hill_ode_stepf2pywrap(4)
      hill_ode_stepf2pywrap = hill_ode_step(state, a_coeffs, b_coeffs, d&
     &t)
      end subroutine f2pywrap_hill_solver_hill_ode_step
      
      subroutine f2pyinithill_solver(f2pysetupfunc)
      use hill_solver, only : solve_hill_problem
      interface 
      subroutine f2pywrap_hill_solver_hill_ode_step (hill_ode_stepf2pywr&
     &ap, hill_ode_step, state, a_coeffs, b_coeffs, dt)
      real(kind=16) dt
      real(kind=16) state(4)
      real(kind=16) a_coeffs(4)
      real(kind=16) b_coeffs(4)
      real(kind=16) hill_ode_step(4)
      real(kind=16) hill_ode_stepf2pywrap(4)
      end subroutine f2pywrap_hill_solver_hill_ode_step
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(solve_hill_problem,f2pywrap_hill_solver_hill_od&
     &e_step)
      end subroutine f2pyinithill_solver


